version: '2'

services:
  filebeat:
    build: ./
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /tmp/data:/mnt/data
    networks:
      - esnet
    #depends_on:

networks:
  esnet:
    driver: bridge
