version: '2'

services:
  elasticsearch:
    container_name: elasticsearch
    build: ./elasticsearch
    command: elasticsearch -Expack.security.enabled=false -Expack.monitoring.enabled=false -Expack.graph.enabled=false -Expack.watcher.enabled=false 
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - esnet
    cap_add:
      - IPC_LOCK
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  filebeat:
    container_name: filebeat
    build: ./filebeat
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /docker/pglogdata:/mnt/data
    depends_on:
      - logstash

  logstash:
    container_name: logstash
    build: ./logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    #ports:
    #  - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - esnet
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    build: ./kibana
    #volumes:
    #  - ./kibana/.kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      XPACK_GRAPH_ENABLED: "false"
      XPACK_MONITORING_ENABLED: "false"
      XPACK_SECURITY_ENABLED: "false"
      XPACK_REPORTING_ENABLED: "false"
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch

  postgres:
    container_name: postgres
    build: ./postgres
    volumes:
      - /docker/pgdata:/pgdata
      - /docker/pglogdata:/tmp
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./postgres/conf.d:/conf.d

volumes:
  esdata:

networks:
  esnet:
    driver: bridge
