version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    build: ./
    command: elasticsearch -Expack.security.enabled=false -Expack.monitoring.enabled=false -Expack.graph.enabled=false -Expack.watcher.enabled=false 
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - es-net
    cap_add:
      - IPC_LOCK
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  filebeat:
    build: ./filebeat
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - pglogdata:/mnt/data
    depends_on:
      - logstash

  logstash:
    build: ./logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - es-net
    depends_on:
      - elasticsearch

  kibana:
    build: ./kibana
    depends_on:
      - elasticsearch

  postgres:
    build: ./postgres
    volumes:
      - pgdata:/pgdata
      - pglogdata:/tmp
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./postgres/conf.d:/conf.d

volumes:
  esdata:
  pglogdata:
  pgdata:

networks:
  es-net:
    driver: bridge
