version: '2'

services:
  elasticsearch:
    extends:
      file: ./elasticsearch/docker-compose.yml
      service: elasticsearch

  logstash:
    extends:
      file: ./logstash/docker-compose.yml
      service: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - pglog:/mnt/data:rw
    depends_on:
      - elasticsearch

  kibana:
    extends:
      file: ./kibana/docker-compose.yml
      service: kibana
    depends_on:
      - elasticsearch

  postgres:
    extends:
      file: ./postgres/docker-compose.yml
      service: postgres

  pgadmin:
    extends:
      file: ./pgadmin/docker-compose.yml
      service: pgadmin

  schemaspy:
    extends:
      file: ./schemaspy/docker-compose.yml
      service: schemaspy
    depends_on:
      - postgres

  schemaspy_nginx:
    extends:
      file: ./schemaspy/docker-compose.yml
      service: schemaspy_nginx
    depends_on:
      - postgres

volumes:
  pgdata:
  pgadmin:
  pglog:
  esdata:
  schemaspydata:

networks:
  pgnet:
    external: true
  esnet:
    driver: bridge
