version: '2'

services:
  master:
    build: ./
    volumes:
      - pgdata:/pgdata
      - pglog:/tmp
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./postgres/conf.d:/conf.d
      - ./postgres/scripts:/scripts
#    ports:
#        - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/pgdata
      - REPLICATION_USER=replicator
#      - REPLICATION_PASSWORD=
    networks:
      - postgres

volumes:
  pgdata:

networks:
  postgres:
