version: '2'

services:
  schemaspy_nginx:
    image: nginx:1.13.1-alpine
    volumes:
      - schemaspydata:/var/www/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
 #   environment:
 #     - LANG=ja_JP.UTF-8
 #     - TZ=Asia/Tokyo
    command: "nginx -g 'daemon off;'"
#    env_file:
#      - ./../env_file

  schemaspy:
    image: schemaspy/schemaspy:snapshot
    volumes:
      - ./schemaspy.properties:/schemaspy.properties
      - schemaspydata:/output
#    environment:
#      - LANG=ja_JP.UTF-8
#      - TZ=Asia/Tokyo
    env_file:
      - ./../env_file
    networks:
      - pgnet

volumes:
  schemaspydata:
